# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'RxMemoTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMemoTutorial

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'


  target 'RxMemoTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxMemoTutorialUITests' do
    # Pods for testing
  end

end
